#ifndef QSTREAM_IOCTL_H
#define QSTREAM_IOCTL_H

#include <linux/ioctl.h>

#define QSTREAM_IOCTL_TYPE  'q'

#define QSTREAM_IOCTL_START _IO(QSTREAM_IOCTL_TYPE, 0x01)
#define QSTREAM_IOCTL_STOP  _IO(QSTREAM_IOCTL_TYPE, 0x02)

#endif