#ifndef QSTREAM_WIRE_H
#define QSTREAM_WIRE_H

/* Local development PCI IDs—not IDs for physical commercial hardware. */
#define QSTREAM_PCI_VENDOR_ID 0x1234
#define QSTREAM_PCI_DEVICE_ID 0x11e9

#define QSTREAM_BAR_INDEX 0
#define QSTREAM_BAR_SIZE  0x1000

#define QSTREAM_REG_MAGIC   0x00
#define QSTREAM_REG_VERSION 0x04
#define QSTREAM_REG_SCRATCH 0x08

#define QSTREAM_REG_IRQ_STATUS 0x0C
#define QSTREAM_REG_IRQ_RAISE  0x10
#define QSTREAM_REG_IRQ_ACK    0x14

#define QSTREAM_IRQ_DATA_READY (1u << 0)

#define QSTREAM_MAGIC   0x51535452u
#define QSTREAM_VERSION 0x00010000u

#define QSTREAM_REG_CONTROL     0x18
#define QSTREAM_REG_FIFO_COUNT  0x1C
#define QSTREAM_REG_DATA_BASE   0x20
#define QSTREAM_REG_FIFO_POP    0x40

#define QSTREAM_CONTROL_GENERATE_ONE (1u << 0)
#define QSTREAM_FIFO_POP_ONE          (1u << 0)

#define QSTREAM_RECORD_WORDS 8u
#define QSTREAM_RECORD_SIZE  32u

#define QSTREAM_WORD_SEQUENCE_LO  0u
#define QSTREAM_WORD_SEQUENCE_HI  1u
#define QSTREAM_WORD_TIMESTAMP_LO 2u
#define QSTREAM_WORD_TIMESTAMP_HI 3u
#define QSTREAM_WORD_VALUE        4u
#define QSTREAM_WORD_GENERATION   5u
#define QSTREAM_WORD_FLAGS        6u
#define QSTREAM_WORD_CHECKSUM     7u

#define QSTREAM_REG_DATA_WORD(word) \
    (QSTREAM_REG_DATA_BASE + ((word) * 4u))

#endif